version: '3'
services:
  notification-serv:
    build: .
    command: /bin/bash
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - db
    volumes:
      - ".:/apps/"
      - "./libs:/root/.m2/repository"

volumes:
  libs:
